packages:
  - "apps/*"
  - "packages/*"

catalog:
  lucide-react: ^0.451.0
  tailwindcss: ^3.4.13
  eslint: ^8.57.0
  prettier: ^3.3.3
  typescript: ^5.6.3
  "@types/node": ^20
  "@types/eslint": ^8

catalogs:
  react19:
    react: ^19.0.0-rc-fb9a90fa48-20240614
    react-dom: ^19.0.0-rc-fb9a90fa48-20240614
    "@types/react": ^18
    "@types/react-dom": ^18
