import "@repo/ui/globals.css";
import localFont from "next/font/local";
import type { Metadata } from "next";
import LayouProvider from "../@/molecules/layout";
import { ThemeProvider } from "../@/providers/theme-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Jsclimber Tech Blog",
  description: "Generated by amiraryan1996",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange={false}
        >
          <LayouProvider>{children}</LayouProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
